spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=120s
  #Release
  datasource:
    url: ${MY_DATABASE_URL}
    username: ${MY_DATABASE_USERNAME}
    password: ${MY_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  #Debug local only
  #datasource:
  #  url: jdbc:mysql://localhost:3306/appslapp
  #  username: computer
  #  password: ${MYSQL_DATABASE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: appslappmanagement@gmail.com
    password: ${APPSLAPP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update

debug: true
server:
  port: ${PORT:8080}

org:
  springframework:
    boot:
      env:
        EnvironmentPostProcessor: org.appslapp.AppsLappServer.business.config.EnvConfig