spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=120s
  #Debug local only
  datasource:
    url: jdbc:mysql://localhost:3306/appslapp
    username: computer
    password: Ratatui je best.

debug: true