spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=120s
  #Release
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mvc:
    log-request-details: true

  #Debug local only
  #datasource:
  #  url: jdbc:mysql://localhost:3306/appslapp
  #  username: computer
  #  password: ${MYSQL_DATABASE_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update

debug: true
server:
  port: ${PORT:8080}

logging:
  level:
    org:
      springframework:
        web: DEBUG
